//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurants.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu
    {
        public int idplato { get; set; }
        public string nombreplato { get; set; }
        public Nullable<int> numeromesa { get; set; }
        public Nullable<int> valor { get; set; }
        public string nombremesero { get; set; }
    }
}
